/**
 * Bundle the menubar demo page.
 *
 * The stylesheet is generated into a module rather than fetched, so the page
 * and `npm run ui:menubar:png` style the tree from exactly the same text and
 * cannot drift. esbuild is resolved out of the conformance host's directory,
 * so there is one install for the playground, the gate and this.
 *
 * It asks for esbuild ALONE, via `requireHostTool`, and not for the reference
 * host `requireDom` demands. Everything bundled here is this repository's own
 * source: nothing on the page imports React or a Radix component. Demanding
 * the reference host as well made this exit 3 on any machine without it —
 * including CI, where the root install supplies esbuild and the host is never
 * installed, so `ui:demo:page` failed there while passing on a developer
 * machine that happened to have run `ui:conformance:install`.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { MissingDomDeps, requireHostTool } from "../../ui/conformance/dom-adapter.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const UI = path.join(HERE, "..");

function requireDom(name) {
  try {
    return requireHostTool(name);
  } catch (e) {
    console.error(e instanceof MissingDomDeps ? e.message : String(e));
    process.exit(3);
  }
}

const DEMOS = ["FilterDemo", "EventCalDemo", "MessageDemo", "ControlsDemo", "MenubarDemo", "ToolbarDemo", "SortableDemo", "MotionDemo", "TableDemo", "DropdownDemo", "DialogDemo", "TreeDemo", "TimelineDemo", "ResizeDemo", "FormDemo", "ProfileDemo", "DashboardDemo", "CalendarDemo", "OtpDemo", "MetadataDemo", "EffectsDemo"];
DEMOS.push("AccordionDemo");
DEMOS.push("SeparatorDemo");
DEMOS.push("TabsDemo");
DEMOS.push("PopoverDemo");
DEMOS.push("AutocompleteDemo");
DEMOS.push("PaginationDemo");
DEMOS.push("RadioGroupDemo");
DEMOS.push("RatingDemo");
DEMOS.push("KanbanDemo");
DEMOS.push("DrawerDemo");
DEMOS.push("ComboboxDemo");
DEMOS.push("ColorPickerDemo");
DEMOS.push("SelectDemo");
for (const name of DEMOS) {
  if (!fs.existsSync(path.join(UI, "bin", name + ".cjs"))) {
    console.error(`compiled ${name} missing — run \`npm run ui:demo:build\` first`);
    process.exit(3);
  }
}

// One-line re-exports, so the page imports paths that are the same in the
// bundle and in the editor rather than reaching into ../bin.
fs.writeFileSync(
  path.join(HERE, "generated-host.js"),
  "// Generated by demo/build.mjs — do not edit.\n" +
    'export { MenubarDemo } from "../bin/MenubarDemo.cjs";\n' +
    'export { ToolbarDemo } from "../bin/ToolbarDemo.cjs";\n' +
    'export { SortableDemo } from "../bin/SortableDemo.cjs";\n' +
    'export { MotionDemo } from "../bin/MotionDemo.cjs";\n' +
    'export { TableDemo } from "../bin/TableDemo.cjs";\n' +
    'export { DropdownDemo } from "../bin/DropdownDemo.cjs";\n' +
    'export { DialogDemo } from "../bin/DialogDemo.cjs";\n' +
    'export { TreeDemo } from "../bin/TreeDemo.cjs";\n' +
    'export { TimelineDemo } from "../bin/TimelineDemo.cjs";\n' +
    'export { ResizeDemo } from "../bin/ResizeDemo.cjs";\n' +
    'export { FormDemo } from "../bin/FormDemo.cjs";\n' +
    'export { ProfileDemo } from "../bin/ProfileDemo.cjs";\n' +
    'export { DashboardDemo } from "../bin/DashboardDemo.cjs";\n' +
    'export { CalendarDemo } from "../bin/CalendarDemo.cjs";\n' +
    'export { FilterDemo } from "../bin/FilterDemo.cjs";\n' +
    'export { EventCalDemo } from "../bin/EventCalDemo.cjs";\n' +
    'export { MessageDemo } from "../bin/MessageDemo.cjs";\n' +
    'export { ControlsDemo } from "../bin/ControlsDemo.cjs";\n' +
    'export { OtpDemo } from "../bin/OtpDemo.cjs";\n' +
    'export { MetadataDemo } from "../bin/MetadataDemo.cjs";\n' +
    'export { EffectsDemo } from "../bin/EffectsDemo.cjs";\n' +
    'export { AccordionDemo } from "../bin/AccordionDemo.cjs";\n' +
    'export { SeparatorDemo } from "../bin/SeparatorDemo.cjs";\n' +
    'export { TabsDemo } from "../bin/TabsDemo.cjs";\n' +
    'export { PopoverDemo } from "../bin/PopoverDemo.cjs";\n' +
    'export { AutocompleteDemo } from "../bin/AutocompleteDemo.cjs";\n' +
    'export { PaginationDemo } from "../bin/PaginationDemo.cjs";\n' +
    'export { RadioGroupDemo } from "../bin/RadioGroupDemo.cjs";\n' +
    'export { RatingDemo } from "../bin/RatingDemo.cjs";\n' +
    'export { KanbanDemo } from "../bin/KanbanDemo.cjs";\n' +
    'export { DrawerDemo } from "../bin/DrawerDemo.cjs";\n' +
    'export { ComboboxDemo } from "../bin/ComboboxDemo.cjs";\n' +
    'export { ColorPickerDemo } from "../bin/ColorPickerDemo.cjs";\n' +
    'export { SelectDemo } from "../bin/SelectDemo.cjs";\n' +
    // The whole modules too, as a list: the browser's text measurer is
    // installed into every one of them (`lib/evg/gl/evg-measure.js`),
    // because two copies of a class are two classes and each compiled demo
    // has its own `EVGDefaultMeasurer`.
    // (`export * as` makes no local binding, so the list below could not
    // name them; an import that is then re-exported does.)
    DEMOS.map((n) => `import * as ${n}Module from "../bin/${n}.cjs";\n`).join("") +
    `export { ${DEMOS.map((n) => n + "Module").join(", ")} };\n` +
    `export const MODULES = [${DEMOS.map((n) => n + "Module").join(", ")}];\n`,
);

const css = (f) => JSON.stringify(fs.readFileSync(path.join(HERE, f), "utf8"));
fs.writeFileSync(
  path.join(HERE, "generated.js"),
  "// Generated by demo/build.mjs — do not edit.\n" +
    `export const MENUBAR_CSS = ${css("menubar.css")};\n` +
    `export const TOOLBAR_CSS = ${css("toolbar.css")};\n` +
    `export const SORTABLE_CSS = ${css("sortable.css")};\n` +
    `export const MOTION_CSS = ${css("motion.css")};\n` +
    `export const TABLE_CSS = ${css("table.css")};\n` +
    `export const DROPDOWN_CSS = ${css("dropdown.css")};\n` +
    `export const DIALOG_CSS = ${css("dialog.css")};\n` +
    `export const TREE_CSS = ${css("tree.css")};\n` +
    `export const TIMELINE_CSS = ${css("timeline.css")};\n` +
    `export const RESIZE_CSS = ${css("resize.css")};\n` +
    `export const FORM_CSS = ${css("form.css")};\n` +
    `export const PROFILE_CSS = ${css("profile.css")};\n` +
    `export const DASHBOARD_CSS = ${css("dashboard.css")};\n` +
    `export const CALENDAR_CSS = ${css("calendar.css")};\n` +
    `export const FILTERS_CSS = ${css("filters.css")};\n` +
    `export const EVENTCAL_CSS = ${css("eventcal.css")};\n` +
    `export const MESSAGE_CSS = ${css("message.css")};\n` +
    `export const CONTROLS_CSS = ${css("controls.css")};\n` +
    `export const OTP_CSS = ${css("otp.css")};\n` +
    `export const METADATA_CSS = ${css("metadata.css")};\n` +
    `export const EFFECTS_CSS = ${css("effects.css")};\n` +
    `export const ACCORDION_CSS = ${css("accordion.css")};\n` +
    `export const SEPARATOR_CSS = ${css("separator.css")};\n` +
    `export const TABS_CSS = ${css("tabs.css")};\n` +
    `export const POPOVER_CSS = ${css("popover.css")};\n` +
    `export const AUTOCOMPLETE_CSS = ${css("autocomplete.css")};\n` +
    `export const PAGINATION_CSS = ${css("pagination.css")};\n` +
    `export const RADIO_CSS = ${css("radio.css")};\n` +
    `export const RATING_CSS = ${css("rating.css")};\n` +
    `export const KANBAN_CSS = ${css("kanban.css")};\n` +
    `export const DRAWER_CSS = ${css("drawer.css")};\n` +
    `export const COMBOBOX_CSS = ${css("combobox.css")};\n` +
    `export const COLORPICKER_CSS = ${css("colorpicker.css")};\n` +
    `export const SELECT_CSS = ${css("select.css")};\n` +
    // NOT ONE OF THIS DIRECTORY'S STYLESHEETS: the presets live with the
    // effects they configure, in `lib/evg/gl`, and are read from there by the
    // contact sheet and by the pixel gate as well. The page carries the FILE,
    // not a copy of the numbers in it, so a preset edited there is the one the
    // picker offers.
    `export const EFFECT_PRESETS_CSS = ${JSON.stringify(
      fs.readFileSync(path.join(HERE, "..", "..", "..", "lib", "evg", "gl", "effect-presets.css"), "utf8"),
    )};\n`,
);

// --- what EVG's CSS understands, read out of the engine ------------------------
//
// The Styles panel's reference and its validator are built from THIS, not from
// a list typed into the page: every property name `EVGElement.setAttribute`
// has a branch for, the pseudo-classes `EVGPseudo.parse` knows, the media
// features `applyFeature` reads, the units `EVGUnit.parse` takes, and so on.
// A property added to the engine shows up in the panel on the next build, and
// one removed stops being offered. Source-scraping is crude, and it is checked:
// `styles-check.mjs` fails if any of these lists comes back empty.
function evgCssFacts() {
  const LIB = path.join(HERE, "..", "..", "..", "lib", "evg");
  const read = (f) => fs.readFileSync(path.join(LIB, f), "utf8");
  const between = (src, from, to) => {
    const a = src.indexOf(from);
    if (a < 0) return "";
    const b = to ? src.indexOf(to, a + from.length) : -1;
    return src.slice(a, b < 0 ? undefined : b);
  };
  const all = (src, re) => [...src.matchAll(re)].map((m) => m[1]);
  const uniq = (xs) => [...new Set(xs)];
  const el = read("EVGElement.rgr");
  const setAttr = between(el, "fn setAttribute:void (name:string value:string)", "sfn isHostProp:boolean");
  // One entry per branch: the names it answers to, and what it does with the
  // value (a colour, a length, a number, a keyword…), read off its body.
  const props = [];
  const branch = /\n {8}if \(([^\n]*?name == "[^\n]*)\) \{\n([\s\S]*?)\n {8}\}/g;
  for (const m of setAttr.matchAll(branch)) {
    const names = all(m[1], /name == "([^"]+)"/g);
    const body = m[2];
    const type = /EVGColor\.parse\(value\)/.test(body) ? "color"
      : /unitOf\(name value\)|boxSides|EVGUnit\.parse/.test(body) ? "length"
      : /EVGGradient\.parse/.test(body) ? "gradient"
      : /to_double|numberOr|to_int/.test(body) ? "number"
      : "keyword";
    props.push({ names, type, rejects: /EVGReject\.note/.test(body) });
  }
  const sheet = read("EVGStyleSheet.rgr");
  const pseudo = all(between(sheet, "sfn parse:int (name:string)", "sfn holds"), /name == "([^"]+)"/g);
  const media = uniq(all(between(sheet, "fn applyFeature:void", "fn parsePx"), /name == "([^"]+)"/g));
  const resetOnLeave = uniq(all(between(sheet, "sfn initialValue:string", "sfn isLayoutProperty"), /name == "([a-z-]+)"/g));
  const paintOnly = uniq(all(between(sheet, "sfn isLayoutProperty:boolean", "fn applyGroup"), /name == "([a-z-]+)"\)\s*\{ return false/g));
  const timingMsg = (sheet.match(/Unsupported timing function \(([^)]*\)[^"]*)\): "/) || [])[1] || "";
  const unit = read("EVGUnit.rgr");
  const units = uniq([
    ...all(unit, /suffix3? == "([a-z]+)"/g),
    ...all(between(unit, "sfn pxPerUnit", "}\n\n"), /suffix == "([a-z]+)"/g),
    ...(/lastChar == 37/.test(unit) ? ["%"] : []),
  ]);
  const unitKeywords = uniq(all(unit, /trimmed == "([a-z-]+)"/g));
  const transformFns = uniq(all(between(el, "fn applyTransform:void", "fn applyTransformOrigin"), /callArgs\(one "([A-Za-z]+)"\)/g));
  const grad = read("EVGGradient.rgr");
  const gradients = uniq(all(grad, /indexOf gradStr "([a-z-]+)"/g));
  const tr = read("EVGTransition.rgr");
  const recon = between(tr, "fn reconcile:void (el:EVGElement)", "fn reconcileColor");
  const transitionable = uniq([
    ...all(recon, /reconcile(?:Color|Number) ?\(el "([a-z-]+)"/g),
    ...all(recon, /reconcileNumberAs\(el "[^"]+" "([a-z-]+)"/g),
    ...all(recon, /reconcileOriginAxis\(el "([a-z-]+)\./g),
  ]);
  const borderWords = uniq(all(between(el, "sfn isBorderStyleWord", "\n    }\n"), /tok == "([a-z]+)"/g));
  return {
    props, pseudo, media, resetOnLeave, paintOnly, units, unitKeywords, transformFns, gradients,
    transitionable, borderWords,
    timing: timingMsg.split(/,\s*/).filter(Boolean),
    fxPrefix: /head == "evg-fx-"/.test(setAttr) ? "evg-fx-" : "",
    atRules: ["@media", "@vars"].filter((a) => sheet.includes(`"${a}"`)),
  };
}
fs.appendFileSync(
  path.join(HERE, "generated.js"),
  `export const EVG_CSS_FACTS = ${JSON.stringify(evgCssFacts())};\n`,
);

const esbuild = requireDom("esbuild");

// The dashboard's chart measures its own axis labels with `UITextRenderer`,
// which owns a `FontManager`, which looks for font FILES — one `existsSync`,
// and nothing else in the whole bundle touches the filesystem.
//
// A browser has no filesystem, so the honest answer to "is there a font file
// at this path" is NO, and that is exactly what this stub says. It is not a
// workaround for a dependency that should not be there: `hasFont` stays false
// and the renderer falls back to its estimating measurer, which is the same
// path the Node gate takes, because the gate registers no font directory
// either. If a real face is ever wanted in the browser it arrives as a fetch,
// not as a file, and this stub goes on telling the truth.
const noFilesystem = {
  name: "no-filesystem",

  setup(build) {
    build.onResolve({ filter: /^(fs|node:fs)$/ }, () => ({
      path: "fs",
      namespace: "stub-fs",
    }));

    build.onLoad({ filter: /.*/, namespace: "stub-fs" }, () => ({
      contents: `
        export const existsSync = () => false;
        export const readFileSync = () => {
          throw new Error("no filesystem in the browser");
        };
        export const readdirSync = () => [];

        export default {
          existsSync,
          readFileSync,
          readdirSync,
        };
      `,
      loader: "js",
    }));

    build.onResolve({ filter: /^(path|node:path)$/ }, () => ({
      path: "path",
      namespace: "stub-path",
    }));

    build.onLoad({ filter: /.*/, namespace: "stub-path" }, () => ({
      contents: `
        export const join = (...parts) =>
          parts
            .filter(Boolean)
            .join("/")
            .replace(/\\\\+/g, "/")
            .replace(/\\/+/g, "/");

        export default {
          join,
        };
      `,
      loader: "js",
    }));
  },
};

await esbuild.build({
  entryPoints: [path.join(HERE, "main.js")],
  bundle: true,
  format: "esm",
  outfile: path.join(HERE, "bundle.js"),
  plugins: [noFilesystem],
  logLevel: "info",
});
